hyperbola/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [path("", views.index, name="index"), path("<slug:slug>/", views.post, name="post")]

hyperbola/contact/urls.py
from django.urls import path

from . import views

app_name = "contact"
urlpatterns = [
    path("", views.index, name="index"),
    path("resume/lopopolo.pdf", views.resume, name="resume_pdf"),
]

hyperbola/urls.py
from django.conf import settings
from django.urls import include, path

from .blog import urls as blog
from .contact import urls as contact
from .core.views import not_found
from .frontpage import urls as frontpage
from .lifestream import urls as lifestream
from .shortlinks import urls as shortlinks

urlpatterns = [
    path("", include(frontpage)),
    path("w/", include(blog)),
    path("contact/", include(contact)),
    path("lifestream/", include(lifestream)),
    path("s/", include(shortlinks)),
    path("404.html", not_found),
] + settings.ENVIRONMENT.additional_urls

hyperbola/blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True)
    publish_date = models.DateField(auto_now_add=True)
    summary = models.TextField()
    post_markdown = models.TextField()

    def get_absolute_url(self):
        return reverse("blog:post", args=[str(self.slug)])

    def __str__(self):
        return self.title

hyperbola/blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post


def index(request):
    posts = Post.objects.order_by("-publish_date", "-pk")
    return render(request, "blog_index.html", {"posts": posts})


def post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, "blog_post.html", {"post": post})

hyperbola/blog/templates/blog_index.html
{% extends "base.html" %}

{% block title %} {{ block.super }} :: Blog {% endblock title %}
{% block section_title %} Blog :: Index {% endblock section_title %}

{% block content %}
{% for post in posts %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="card mb-3">
      <div class="card-body">
        <h2 class="card-title">
          <a href="{{ post.get_absolute_url }}">{{ post.title|escape }}</a>
        </h2>
        <h6 class="card-subtitle mb-2 text-muted">
          <a href="{% url "contact:index" %}">Ryan Lopopolo</a> | {{ post.publish_date|date:"F d, Y" }}
        </h6>
        <div class="card-text">{{ post.summary|escape }}</div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

hyperbola/blog/templates/blog_post.html
{% extends "base.html" %}
{% load hyperbola_core_tags %}

{% block title %} {{ block.super }} :: {{ post.title|escape }} {% endblock title %}
{% block section_title %} Blog :: {{ post.title|escape }} {% endblock section_title %}
{% block head %}
{{ block.super }}
<meta property="og:type" content="article" />
<meta property="og:article:published_time" content="{{ post.publish_date|date:"Y-m-d" }}" />
<meta property="og:article:modified_time" content="{{ post.publish_date|date:"Y-m-d" }}" />
<meta property="og:article:author" content="https://www.facebook.com/ryan.lopopolo" />
<meta property="og:title" content="{{ post.title|escape }}" />
<meta property="og:description" content="{{ post.summary|escape }}" />
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="card mb-3">
      <div class="card-body">
        <h2 class="card-title text-center">
          <a href="{{ post.get_absolute_url }}">{{ post.title|escape }}</a>
        </h2>
        <h6 class="card-subtitle text-center mb-2 text-muted">
          <a href="{% url "contact:index" %}">Ryan Lopopolo</a> | {{ post.publish_date|date:"F d, Y" }}
        </h6>
        <div class="card-text">{{ post.post_markdown|markdown }}</div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}